spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.11:1433;database=stardb
    username: staradmin
    password: StarAdmin007
    driver-class_name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        default_schema: dbo
